### ISSUE TITLE
Error when setting up

### ISSUE THREAD

**Issue by joeynimu** [alexluong/gatsby-plugin-firebase#3]
I have followed the documentation but I get the below error when I run `gatsby develop` after setting up my `envs` and `gatsby-config`

```

  Error: ./node_modules/gatsby-plugin-firebase/gatsby-ssr.js 5:2
  Module parse failed: Unexpected token (5:2)
  You may need an appropriate loader to handle this file type.
  | 
  | export const wrapRootElement = ({ element, props }, pluginOptions) => (
  >   <Layout {...props} features={pluginOptions.features}>
  |     {element}
  |   </Layout>
   @ ./.cache/api-runner-ssr.js 46:10-114
   @ ./.cache/develop-static-entry.js
```

My `gatsby info` has the below;

```
System:
    OS: macOS 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.3.0 - ~/.nvm/versions/node/v10.3.0/bin/node
    Yarn: 1.17.3 - ~/.yarn/bin/yarn
    npm: 6.9.0 - ~/.nvm/versions/node/v10.3.0/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 77.0.3865.90
    Safari: 13.0.2
  npmPackages:
    gatsby: ^2.4.3 => 2.4.3 
    gatsby-cli: ^2.7.28 => 2.7.28 
    gatsby-image: ^2.0.41 => 2.0.41 
    gatsby-plugin-firebase: ^0.1.1 => 0.1.1 
    gatsby-plugin-google-analytics: ^2.1.4 => 2.1.4 
    gatsby-plugin-manifest: ^2.1.1 => 2.1.1 
    gatsby-plugin-offline: ^2.1.0 => 2.1.0 
    gatsby-plugin-prefetch-google-fonts: ^1.4.2 => 1.4.2 
    gatsby-plugin-react-helmet: ^3.0.12 => 3.0.12 
    gatsby-plugin-root-import: ^2.0.5 => 2.0.5 
    gatsby-plugin-sass: ^2.0.11 => 2.0.11 
    gatsby-plugin-sharp: ^2.0.37 => 2.0.37 
    gatsby-plugin-styled-components: ^3.1.1 => 3.1.2 
    gatsby-source-filesystem: ^2.0.33 => 2.0.33 
    gatsby-source-graphql: ^2.0.18 => 2.0.19 
    gatsby-transformer-sharp: ^2.1.19 => 2.1.19 
```

**Comment by alexluong** [comment]
Hey, this error message is quite ambiguous. Any chance you're using Flow or TypeScript?

I see that there is a similar-ish issue in the Gatsby repo, and TS seems to be the problem:

https://github.com/gatsbyjs/gatsby/issues/7398

I also set up an barebone site that uses `gatsby-plugin-firebase` on branch [example](https://github.com/alexluong/gatsby-plugin-firebase/tree/example) if you want to check it out.

Lastly, if these are not helpful, if you can set up a minimal reproduction of this issue, I'd be able to help out more.

**Comment by alexluong** [comment]
Also, I see that you're using Gatsby version `2.4.3`. There can potentially be an issue there. Any chance you can take this opportunity to update to the latest versions of your packages?

**Comment by joeynimu** [comment]
@alexluong Thanks for this. Updating `gatsby` seemed to fix it. Closing this for now.
