### ISSUE TITLE
Documentation on gatsby.org

### ISSUE THREAD

**Issue by rafalluksza** [alexluong/gatsby-plugin-firebase#4]
Hi Alex,
thanks for making such a helpful plugin. I think there is a mistake in fragment about dotenv library and how to use it: 
https://www.gatsbyjs.org/packages/gatsby-plugin-firebase/#usefirebase

> require("dotenv").require()
> module.exports = {
>   ...
> }

I found that here in yours documentation it's written like that: 

> require("dotenv").config()
> 
> module.exports = {
>   ...
> }

And it works!

Best regards!
Rafał

**Comment by alexluong** [comment]
Thank you @rafalluksza for reporting the issue. There is a mistake in my initial documentation. I will publish a new patch with the fix right away.
